#include "/Engine/Public/Platform.ush"


void MainVS(
    in float4 InPosition : ATTRIBUTE0,
    out float4 Output : SV_POSITION)
{
    Output = InPosition;
}

float2 ViewportSize;

Texture2D SceneColorTexture;
SamplerState SceneColorSampler;

float4 SimpleColor;


float4 MainPS(float4 ScreenPosition : SV_Position) : SV_Target0
{
	float2 UV = ScreenPosition.xy / ViewportSize;
	float4 SceneColor = SceneColorTexture.Sample(SceneColorSampler, UV);
	return SceneColor * SimpleColor;
}